import { Aseprite } from '@/atlas-pack'
import { Immutable } from '@/ooz'

/**
 * The identifiers for all the films in the atlas. IDs are used to reference
 * immutable image source properties, such as dimensions and animation duration,
 * from the Atlas. The tag convention used here is
 * `<file stem>[-<state or variant>]*`.
 */
export type SPFilmID = Parameters<typeof SPFilmID.values['has']>[0]

export namespace SPFilmID {
  export const values = Immutable(
    new Set(
      [
        'background--Corner',
        'background--Checkerboard', // For debugging.
        'background--Grid',
        'cursor--Pick',
        'cursor--Point',
        'card--CA',
        'card--C2',
        'card--C3',
        'card--C4',
        'card--C5',
        'card--C6',
        'card--C7',
        'card--C8',
        'card--C9',
        'card--C10',
        'card--CJ',
        'card--CQ',
        'card--CK',
        'card--DA',
        'card--D2',
        'card--D3',
        'card--D4',
        'card--D5',
        'card--D6',
        'card--D7',
        'card--D8',
        'card--D9',
        'card--D10',
        'card--DJ',
        'card--DQ',
        'card--DK',
        'card--HA',
        'card--H2',
        'card--H3',
        'card--H4',
        'card--H5',
        'card--H6',
        'card--H7',
        'card--H8',
        'card--H9',
        'card--H10',
        'card--HJ',
        'card--HQ',
        'card--HK',
        'card--SA',
        'card--S2',
        'card--S3',
        'card--S4',
        'card--S5',
        'card--S6',
        'card--S7',
        'card--S8',
        'card--S9',
        'card--S10',
        'card--SJ',
        'card--SQ',
        'card--SK',
        'card--Down',
        'card--VacantClubs',
        'card--VacantDiamonds',
        'card--VacantHearts',
        'card--VacantSpades',
        'card--VacantPile',
        'card--VacantStock',
        'card--OutlineChecked', // Unused
        'card--OutlineFocus', // Unused
        'palette--Alpha',
        'palette--Dark',
        'palette--Light',
        'palette--Mid',
        'patience-the-demon--Good',
        'patience-the-demon--Evil',
        'tally--0',
        'tally--1',
        'tally--2',
        'tally--3',
        'tally--4',
        'tally--5',
        'tally--6',
        'tally--7',
        'tally--8',
        'tally--9',
        'tally--10',
        'tally--11',
        'tally--12',
        'tally--13',
        'tally--14',
        'tally--15',
        'tally--16',
        'tally--17',
        'tally--18',
        'tally--19',
        'tally--20',
      ] satisfies Aseprite.FileTag[],
    ),
  )
}
