import { Immutable } from '@/oidlib';

/**
 * The identifiers for all the films in the atlas. IDs are used to reference
 * immutable image source properties, such as dimensions and animation duration,
 * from the Atlas. The tag convention used here is
 * `<file stem>[-<state or variant>]*`.
 */
export type SPFilmID = Parameters<typeof SPFilmID.values['has']>[0];

export namespace SPFilmID {
  export const values = Immutable(
    new Set(
      [
        'CardCA',
        'CardC2',
        'CardC3',
        'CardC4',
        'CardC5',
        'CardC6',
        'CardC7',
        'CardC8',
        'CardC9',
        'CardC10',
        'CardCJ',
        'CardCQ',
        'CardCK',
        'CardDA',
        'CardD2',
        'CardD3',
        'CardD4',
        'CardD5',
        'CardD6',
        'CardD7',
        'CardD8',
        'CardD9',
        'CardD10',
        'CardDJ',
        'CardDQ',
        'CardDK',
        'CardHA',
        'CardH2',
        'CardH3',
        'CardH4',
        'CardH5',
        'CardH6',
        'CardH7',
        'CardH8',
        'CardH9',
        'CardH10',
        'CardHJ',
        'CardHQ',
        'CardHK',
        'CardSA',
        'CardS2',
        'CardS3',
        'CardS4',
        'CardS5',
        'CardS6',
        'CardS7',
        'CardS8',
        'CardS9',
        'CardS10',
        'CardSJ',
        'CardSQ',
        'CardSK',
        'CardDown',
        'CardVacantClubs',
        'CardVacantDiamonds',
        'CardVacantHearts',
        'CardVacantSpades',
        'CardVacantPile',
        'CardVacantStock',
        'CardOutlineChecked', // Unused
        'CardOutlineFocus', // Unused
        'Corner',
        'CursorPick',
        'CursorPoint',
        'Grid',
        'PaletteAlpha',
        'PaletteDark',
        'PaletteLight',
        'PaletteMid',
        'PatienceTheDemonGood',
        'PatienceTheDemonEvil',
        'Tally0',
        'Tally1',
        'Tally2',
        'Tally3',
        'Tally4',
        'Tally5',
        'Tally6',
        'Tally7',
        'Tally8',
        'Tally9',
        'Tally10',
      ] as const,
    ),
  );
}
